PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE SETTINGS(
NAME TEXT NOT NULL,
UPPER INTEGER NOT NULL,
LOWER INTEGER NOT NULL,
INTERVAL INTEGER NOT NULL
);
CREATE TABLE EVENTS(
ID INTEGER NOT NULL PRIMARY KEY,
TYPE TEXT NOT NULL,
TIMESTAMP NUMERIC NOT NULL
);
CREATE TABLE MEASUREMENTS(
ID INTEGER NOT NULL PRIMARY KEY,
VALUE INTEGER NOT NULL,
TIMESTAMP NUMERIC NOT NULL
);
COMMIT;
