PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE SETTINGS(
NAME TEXT NOT NULL,
UPPER INTEGER NOT NULL,
LOWER INTEGER NOT NULL,
INTERVAL INTEGER NOT NULL
);
CREATE TABLE EVENTS(
TYPE TEXT NOT NULL,
TIMESTAMP NUMERIC NOT NULL
);
CREATE TABLE MEASUREMENT(
VALUE INTEGER NOT NULL,
TIMESTAMP NUMERIC NOT NULL
);
COMMIT;
